# Generated by Django 2.1.7 on 2019-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190410_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
