# Generated by Django 2.1.7 on 2019-05-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190410_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllComment',
            fields=[
                ('comment_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posts.Comment')),
                ('comment', models.TextField(max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_allcomments',
                'managed': False,
            },
        ),
    ]
