# Generated by Django 2.1.7 on 2019-05-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190410_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllComment',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posts.Comment')),
            ],
            options={
                'db_table': 'view_allcomments',
                'managed': False,
            },
        ),
    ]
