# Generated by Django 2.2.1 on 2019-05-13 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
