# Generated by Django 2.2 on 2019-04-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190410_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
